# Generated by Django 4.2.7 on 2025-12-18 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(help_text='Patente única', max_length=10, unique=True)),
                ('marca', models.CharField(help_text='Marca del vehículo', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo del vehículo', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuario responsable del vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['patente'],
            },
        ),
    ]
