# Generated by Django 4.2.7 on 2025-12-18 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['patente'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el vehículo está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(help_text='Marca del vehículo', max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(help_text='Modelo del vehículo', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(db_index=True, help_text='Patente única del vehículo', max_length=10, unique=True, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario responsable del vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['patente'], name='vehiculos_v_patente_48e85b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['usuario'], name='vehiculos_v_usuario_c642a5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['activo'], name='vehiculos_v_activo_e6f381_idx'),
        ),
    ]
