# Generated by Django 4.2.7 on 2025-12-25 21:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos', '0002_alter_vehiculo_options_vehiculo_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.RemoveIndex(
            model_name='vehiculo',
            name='vehiculos_v_usuario_c642a5_idx',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el vehículo está apto para circulación.', verbose_name='Estado Operativo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(db_index=True, help_text='Patente única (Formato: ABCD12 o AB1234).', max_length=10, unique=True, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario asignado actualmente al vehículo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flota', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
    ]
